<?php
/**
 * AbstractRegenerateRewrites.php
 *
 * @package OlegKoval_RegenerateUrlRewrites
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2017-2067 Oleg Koval
 * @license OSL-3.0, AFL-3.0
 */

namespace OlegKoval\RegenerateUrlRewrites\Model;

use OlegKoval\RegenerateUrlRewrites\Api\ChangeListenerInterface;
use OlegKoval\RegenerateUrlRewrites\Api\Data\ChangeInterface;
use OlegKoval\RegenerateUrlRewrites\Api\ProgressReporterInterface;
use OlegKoval\RegenerateUrlRewrites\Helper\Regenerate as RegenerateHelper;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\DB\Adapter\AdapterInterface;
use Magento\Framework\Model\AbstractModel;
use Magento\UrlRewrite\Model\Storage\DbStorage;
use Magento\CatalogUrlRewrite\Model\ResourceModel\Category\Product as ProductUrlRewriteResource;

abstract class AbstractRegenerateRewrites
{
    /**
     * Failure message once the transaction around the run is gone (see _beginTransaction())
     */
    public const ERROR_TRANSACTION_LOST = 'the surrounding database transaction was lost (e.g. to a deadlock),'
        . ' so nothing more is saved in it';

    /**
     * @var string
     */
    protected $entityType = 'product';

    /**
     * @var array
     */
    protected $storeRootCategoryId = [];

    /**
     * Receives progress while the "showProgress" option is on; null: progress is not reported
     * @var ProgressReporterInterface|null
     */
    protected ?ProgressReporterInterface $progressReporter = null;

    /**
     * Receives every DB change; null: changes are not tracked (no extra queries)
     * @var ChangeListenerInterface|null
     */
    protected ?ChangeListenerInterface $changeListener = null;

    /**
     * Changes of the entity being processed, passed to the listener by _flushChanges() — outside the per-entity
     * failure handling, so an exception from the listener stops the run instead of counting as a failure
     * @var ChangeInterface[]
     */
    protected array $pendingChanges = [];

    /**
     * Transactions opened by _beginTransaction(), innermost last: a savepoint name, or null for an adapter
     * transaction
     * @var array<int, string|null>
     */
    private array $transactionStack = [];

    /**
     * A savepoint couldn't be rolled back: the server ended the caller's transaction, so a statement now would
     * commit at once, out of the caller's control
     * @var bool
     */
    private bool $transactionLost = false;

    /**
     * url_rewrite columns a change reports, in this order
     */
    private const REWRITE_COLUMNS = [
        'request_path', 'target_path', 'redirect_type', 'store_id', 'entity_type', 'entity_id', 'is_autogenerated',
        'description', 'metadata',
    ];

    /**
     * @var string
     */
    protected $mainDbTable;

    /**
     * @var string
     */
    protected $secondaryDbTable;

    /**
     * @var string
     */
    protected $categoryProductsDbTable;

    /**
     * Regenerate Rewrites custom options
     * @var array
     */
    protected $regenerateOptions = [];

    /**
     * Default regenerate options, merged under whatever setRegenerateOptions() receives
     * @var array
     */
    protected array $defaultRegenerateOptions = [
        'saveOldUrls' => false,
        'categoriesFilter' => [],
        'productsFilter' => [],
        'categoryId' => null,
        'productId' => null,
        'regenUrlKey' => false,
        'showProgress' => false,
        'skipProducts' => false,
        'skipExisting' => false,
        'includeNotVisible' => false,
        'addSkuToUrl' => false,
        'defaultScopeOnly' => false,
        'skipSecondaryTableUpdate' => false,
        'exactCategories' => false,
        'progressPassStarted' => false,
        'dryRun' => false,
    ];

    /**
     * Max failure details retained; beyond it only counts grow, so a systemic error on a large catalog
     * can't exhaust memory
     */
    protected const FAILURE_DETAILS_LIMIT = 1000;

    /**
     * First FAILURE_DETAILS_LIMIT failures collected since the last resetFailures() call
     * @var array<int, array{entity_type: string, entity_id: int|null, store_id: int|null, message: string}>
     */
    protected array $failures = [];

    /**
     * Exact failure count per entity type since the last resetFailures() call
     * @var array<string, int>
     */
    protected array $failureCounts = [];

    /**
     * Entities gone through since the last resetProcessedCounts() call: entity type => store ID => count
     * @var array<string, array<int, int>>
     */
    protected array $processedCounts = [];

    /**
     * @var RegenerateHelper
     */
    protected $helper;

    /**
     * @var ResourceConnection
     */
    protected $resourceConnection;

    /**
     * RegenerateAbstract constructor
     *
     * @param RegenerateHelper $helper
     * @param ResourceConnection $resourceConnection
     */
    public function __construct(
        RegenerateHelper   $helper,
        ResourceConnection $resourceConnection
    )
    {
        $this->helper = $helper;
        $this->resourceConnection = $resourceConnection;
        $this->regenerateOptions = $this->defaultRegenerateOptions;
    }

    /**
     * Set regenerate options; keys not given fall back to the defaults
     *
     * Merges over the defaults rather than the current options, since model instances are shared
     * (e.g. the category model re-sets the product model's options per category) and a previous
     * call's keys must not leak into the next one.
     *
     * @param array $options
     * @return void
     */
    public function setRegenerateOptions(array $options): void
    {
        $this->regenerateOptions = array_merge($this->defaultRegenerateOptions, $options);
    }

    abstract function regenerate(int $storeId = 0);

    /**
     * First FAILURE_DETAILS_LIMIT failures since the last resetFailures() call (see getFailureCounts() for totals)
     *
     * @return array<int, array{entity_type: string, entity_id: int|null, store_id: int|null, message: string}>
     */
    public function getFailures(): array
    {
        return $this->failures;
    }

    /**
     * Exact failure count per entity type since the last resetFailures() call
     *
     * @return array<string, int>
     */
    public function getFailureCounts(): array
    {
        return $this->failureCounts;
    }

    /**
     * Clear collected failures
     *
     * Never called from inside a run: the command calls regenerate() once per store and the category
     * model reuses the product model per category, so an implicit reset would drop earlier failures.
     *
     * @return $this
     */
    public function resetFailures(): static
    {
        $this->failures = [];
        $this->failureCounts = [];

        return $this;
    }

    /**
     * Entities gone through (incl. failed and skipped ones) since the last resetProcessedCounts() call
     *
     * @return array<string, array<int, int>> entity type => store ID => count
     */
    public function getProcessedCounts(): array
    {
        return $this->processedCounts;
    }

    /**
     * Start a run over one or more stores: clears failures, counts and whatever a model carries from one store's pass
     * to the next
     *
     * @return $this
     */
    public function startRun(): static
    {
        $this->resetFailures();
        $this->resetProcessedCounts();
        $this->transactionStack = [];
        $this->transactionLost = false;

        return $this;
    }

    /**
     * @return $this
     */
    public function resetProcessedCounts(): static
    {
        $this->processedCounts = [];

        return $this;
    }

    /**
     * @param int $storeId
     * @return void
     */
    protected function _countProcessed(int $storeId): void
    {
        $count = $this->processedCounts[$this->entityType][$storeId] ?? 0;
        $this->processedCounts[$this->entityType][$storeId] = $count + 1;
    }

    /**
     * @param string $entityType
     * @param int|null $entityId null for a failure not tied to a single entity (e.g. a cleanup step)
     * @param int|null $storeId
     * @param string $message
     * @return void
     */
    protected function _addFailure(string $entityType, ?int $entityId, ?int $storeId, string $message): void
    {
        $this->failureCounts[$entityType] = ($this->failureCounts[$entityType] ?? 0) + 1;

        if (count($this->failures) >= static::FAILURE_DETAILS_LIMIT) {
            return;
        }

        $this->failures[] = [
            'entity_type' => $entityType,
            'entity_id' => $entityId,
            'store_id' => $storeId,
            'message' => $message,
        ];
    }

    /**
     * Return resource connection
     * @return ResourceConnection
     */
    protected function _getResourceConnection(): ResourceConnection
    {
        return $this->resourceConnection;
    }

    /**
     * Save Url Rewrites
     *
     * @param array $urlRewrites
     * @param array $entityData
     * @return $this
     */
    public function saveUrlRewrites(array $urlRewrites, array $entityData = []): static
    {
        $data = $this->_prepareUrlRewrites($urlRewrites);

        // every generated path was empty: nothing to write, so keep the current rewrites (an empty
        // insertOnDuplicate() builds column-less SQL, which either fails or commits after the delete)
        if (empty($data)) {
            return $this;
        }

        if (empty($entityData)) {
            $entityData = $data;
        }

        // the generated set replaces the entity's current rows even with --save-old-urls, as Magento's
        // own UrlPersist does: the generator has already turned each old URL into a 301 (save_rewrites_history)
        // and re-emitted custom rows. Keeping the old rows instead made each 301 collide with its old row on
        // the unique key, and insertOnDuplicate() only updates request_path/metadata, so the 301 was lost and
        // the old URL kept serving the page (see #174, #142).
        // delete + insert run in a single transaction so a failed insert can't leave an entity
        // with its old rewrites deleted and nothing to replace them (see #137)
        $connection = $this->_getResourceConnection()->getConnection();
        $committed = false;
        $this->_beginTransaction($connection);
        try {
            // to report the changes (only when someone listens): the rows being replaced plus whatever holds the new
            // paths already — a row outside the replaced set (e.g. of a sibling store view) is updated by
            // insertOnDuplicate(), not inserted — and afterwards what the table really holds at the new paths
            $oldRows = $this->changeListener !== null
                ? $this->_fetchRewrites(
                    '(' . $this->_getCurrentRewritesWhere($entityData) . ') OR (' . $this->_getPathsWhere($data) . ')'
                )
                : [];
            $this->_deleteCurrentRewrites($entityData);

            $connection->insertOnDuplicate(
                $this->_getMainTableName(),
                $data,
                ['request_path', 'metadata']
            );
            $this->_commitTransaction($connection);
            $committed = true;
        } catch (\Exception $e) {
            $this->_rollBackTransaction($connection);

            // one failure per entity whose rewrites were not saved (a category call can include children)
            $failed = [];
            foreach ($entityData ?: $data as $row) {
                $failed[$row['entity_type'] . '|' . $row['entity_id'] . '|' . $row['store_id']] = $row;
            }
            foreach ($failed as $row) {
                $this->_addFailure(
                    (string)$row['entity_type'],
                    (int)$row['entity_id'],
                    (int)$row['store_id'],
                    'saving URL rewrites failed: ' . $e->getMessage()
                );
            }
        }

        // after the transaction: a failing read here must not roll back or fail a save that is committed
        if ($committed && $this->changeListener !== null) {
            try {
                $this->_queueRewriteChanges($oldRows, $this->_fetchRewrites($this->_getPathsWhere($data)));
            } catch (\Exception $e) {
                $row = reset($entityData);
                $this->_addFailure(
                    (string)$row['entity_type'],
                    (int)$row['entity_id'],
                    (int)$row['store_id'],
                    'URL rewrites saved, but reading them for the change listener failed: ' . $e->getMessage()
                );
            }
        }

        return $this;
    }

    /**
     * @param ProgressReporterInterface|null $reporter null: stop reporting progress
     * @return $this
     */
    public function setProgressReporter(?ProgressReporterInterface $reporter): static
    {
        $this->progressReporter = $reporter;

        return $this;
    }

    /**
     * @param ChangeListenerInterface|null $listener null: stop tracking changes
     * @return $this
     */
    public function setChangeListener(?ChangeListenerInterface $listener): static
    {
        $this->changeListener = $listener;
        $this->pendingChanges = [];

        return $this;
    }

    /**
     * Pass the queued changes to the listener
     *
     * @return void
     */
    protected function _flushChanges(): void
    {
        $changes = $this->pendingChanges;
        $this->pendingChanges = [];
        if ($this->changeListener === null) {
            return;
        }
        foreach ($changes as $change) {
            $this->changeListener->onChange($change);
        }
    }

    /**
     * Queue what replacing $oldRows with $newRows changed, keyed by store + request path as the table is
     *
     * @param array[] $oldRows url_rewrite rows before the save
     * @param array[] $newRows rows written
     * @return void
     */
    protected function _queueRewriteChanges(array $oldRows, array $newRows): void
    {
        $old = $new = [];
        foreach ($oldRows as $row) {
            $row = $this->_normalizeRewriteRow($row);
            $old[$row['store_id'] . '|' . $row['request_path']] = $row;
        }
        foreach ($newRows as $row) {
            $row = $this->_normalizeRewriteRow($row);
            $new[$row['store_id'] . '|' . $row['request_path']] = $row;
        }

        foreach ($old as $key => $row) {
            if (!isset($new[$key])) {
                $this->_queueRewriteChange(ChangeInterface::TYPE_REWRITE_REMOVED, $row, null);
            } elseif ($new[$key] != $row) {
                $this->_queueRewriteChange(ChangeInterface::TYPE_REWRITE_UPDATED, $row, $new[$key]);
            }
        }
        foreach ($new as $key => $row) {
            if (!isset($old[$key])) {
                $this->_queueRewriteChange(ChangeInterface::TYPE_REWRITE_ADDED, null, $row);
            }
        }
    }

    /**
     * @param string $type
     * @param array|null $oldRow
     * @param array|null $newRow
     * @return void
     */
    private function _queueRewriteChange(string $type, ?array $oldRow, ?array $newRow): void
    {
        $row = $newRow ?? $oldRow;
        $this->pendingChanges[] = new Change(
            $type,
            (string)$row['entity_type'],
            $row['entity_id'],
            $row['store_id'],
            $oldRow['request_path'] ?? null,
            $newRow['request_path'] ?? null,
            $oldRow,
            $newRow
        );
    }

    /**
     * @param array $row a url_rewrite row, from the table or as prepared for saving
     * @return array the REWRITE_COLUMNS, typed, metadata decoded
     */
    private function _normalizeRewriteRow(array $row): array
    {
        $normalized = [];
        foreach (self::REWRITE_COLUMNS as $column) {
            $normalized[$column] = $row[$column] ?? null;
        }
        $normalized['redirect_type'] = (int)$normalized['redirect_type'];
        $normalized['store_id'] = (int)$normalized['store_id'];
        $normalized['entity_id'] = $normalized['entity_id'] === null ? null : (int)$normalized['entity_id'];
        $normalized['is_autogenerated'] = (int)$normalized['is_autogenerated'];
        $metadata = $normalized['metadata'];
        if (is_string($metadata)) {
            $metadata = $metadata === '' ? null : json_decode($metadata, true);
        }
        $normalized['metadata'] = is_array($metadata) && count($metadata) > 0 ? $metadata : null;

        return $normalized;
    }

    /**
     * The url_key and url_path rows of an entity in the given stores, read to report attribute changes
     *
     * @param AbstractModel $entity product/category as loaded by its collection (incl. its link field)
     * @param int[] $storeIds
     * @return array<string, array<int, array{0: bool, 1: string|null}>> attribute code => store ID => [row exists,
     *         value] — a row can exist and hold NULL
     */
    protected function _readUrlAttributes(AbstractModel $entity, array $storeIds): array
    {
        $resource = $entity->getResource();
        $linkField = $resource->getLinkField();
        $codes = [];
        foreach (['url_key', 'url_path'] as $code) {
            $codes[(int)$resource->getAttribute($code)->getId()] = $code;
        }

        $values = [];
        foreach ($codes as $code) {
            $values[$code] = array_fill_keys($storeIds, [false, null]);
        }
        $connection = $resource->getConnection();
        $select = $connection->select()
            ->from($resource->getAttribute('url_key')->getBackend()->getTable(), ['attribute_id', 'store_id', 'value'])
            ->where('attribute_id IN (?)', array_keys($codes))
            ->where($linkField . ' = ?', (int)$entity->getData($linkField))
            ->where('store_id IN (?)', $storeIds);
        foreach ($connection->fetchAll($select) as $row) {
            $values[$codes[(int)$row['attribute_id']]][(int)$row['store_id']] = [true, $row['value']];
        }

        return $values;
    }

    /**
     * @param AbstractModel $entity
     * @param array<string, array<int, array{0: bool, 1: string|null}>> $before as _readUrlAttributes() returns it
     * @param array<string, array<int, array{0: bool, 1: string|null}>> $after
     * @return void
     */
    protected function _queueAttributeChanges(AbstractModel $entity, array $before, array $after): void
    {
        $types = [
            'url_key' => ChangeInterface::TYPE_URL_KEY_CHANGED,
            'url_path' => ChangeInterface::TYPE_URL_PATH_CHANGED,
        ];
        foreach ($before as $code => $values) {
            foreach ($values as $storeId => [$hadRow, $value]) {
                [$hasRow, $newValue] = $after[$code][$storeId];
                if ($hadRow !== $hasRow || $value !== $newValue) {
                    $this->pendingChanges[] = new Change(
                        $types[$code],
                        $this->entityType,
                        (int)$entity->getId(),
                        $storeId,
                        $value,
                        $newValue,
                        null,
                        null,
                        $hadRow,
                        $hasRow
                    );
                }
            }
        }
    }

    /**
     * @param int $storeId
     * @param int $total
     * @return void
     */
    protected function _progressStart(int $storeId, int $total): void
    {
        // internal option: the caller runs several batches as one reported pass and started it itself
        if ($this->regenerateOptions['progressPassStarted']) {
            return;
        }
        if ($this->regenerateOptions['showProgress'] && $this->progressReporter !== null) {
            $this->progressReporter->start($this->entityType, $storeId, $total);
        }
    }

    /**
     * @return void
     */
    protected function _progressAdvance(): void
    {
        if ($this->regenerateOptions['showProgress'] && $this->progressReporter !== null) {
            $this->progressReporter->advance();
        }
    }

    /**
     * @return void
     */
    protected function _progressFinish(): void
    {
        if ($this->regenerateOptions['progressPassStarted']) {
            return;
        }
        if ($this->regenerateOptions['showProgress'] && $this->progressReporter !== null) {
            $this->progressReporter->finish();
        }
    }

    /**
     * @return string
     */
    protected function _getMainTableName(): string
    {
        if (empty($this->mainDbTable)) {
            $this->mainDbTable = $this->_getResourceConnection()->getTableName(DbStorage::TABLE_NAME);
        }

        return $this->mainDbTable;
    }

    /**
     * @return string
     */
    protected function _getSecondaryTableName(): string
    {
        if (empty($this->secondaryDbTable)) {
            $this->secondaryDbTable = $this->_getResourceConnection()->getTableName(ProductUrlRewriteResource::TABLE_NAME);
        }

        return $this->secondaryDbTable;
    }

    /**
     * @return string
     */
    protected function _getCategoryProductsTableName(): string
    {
        if (empty($this->categoryProductsDbTable)) {
            $this->categoryProductsDbTable = $this->_getResourceConnection()->getTableName('catalog_category_product');
        }

        return $this->categoryProductsDbTable;
    }

    /**
     * Delete current Url Rewrites
     *
     * @param array $entitiesData
     * @return $this
     */
    protected function _deleteCurrentRewrites(array $entitiesData = []): static
    {
        if (!empty($entitiesData)) {
            // transaction is managed by the caller (saveUrlRewrites()), so delete + insert commit
            // or roll back together (see #137)
            $this->_getResourceConnection()->getConnection()->delete(
                $this->_getMainTableName(),
                $this->_getCurrentRewritesWhere($entitiesData)
            );
        }

        return $this;
    }

    /**
     * @param string $where
     * @return array[]
     */
    protected function _fetchRewrites(string $where): array
    {
        $connection = $this->_getResourceConnection()->getConnection();

        return $connection->fetchAll($connection->select()->from($this->_getMainTableName())->where($where));
    }

    /**
     * @param array[] $rows rows with store_id, request_path
     * @return string the url_rewrite rows at those store + request paths (the table's unique key)
     */
    protected function _getPathsWhere(array $rows): string
    {
        $connection = $this->_getResourceConnection()->getConnection();
        $conditions = [];
        foreach ($rows as $row) {
            $conditions[] = '('
                . $connection->quoteInto('store_id = ?', (int)$row['store_id'])
                . $connection->quoteInto(' AND request_path = ?', (string)$row['request_path'])
                . ')';
        }

        return implode(' OR ', array_unique($conditions));
    }

    /**
     * @param array $entitiesData rows with entity_type, entity_id, store_id
     * @return string the url_rewrite rows of those entities in those stores
     */
    protected function _getCurrentRewritesWhere(array $entitiesData): string
    {
        $whereConditions = [];
        $connection = $this->_getResourceConnection()->getConnection();
        foreach ($entitiesData as $entityData) {
            $whereConditions[] = '('
                . $connection->quoteInto('entity_type = ?', $entityData['entity_type'])
                . $connection->quoteInto(' AND entity_id = ?', (int)$entityData['entity_id'])
                . $connection->quoteInto(' AND store_id = ?', (int)$entityData['store_id'])
                . ')';
        }

        return implode(' OR ', array_unique($whereConditions));
    }

    /**
     * Delete url_rewrite rows (for this entity type) whose product/category no longer exists (see #158)
     *
     * @return $this
     */
    public function deleteOrphanedRewrites(): static
    {
        $entityTable = $this->_getResourceConnection()->getTableName(
            $this->entityType === 'category' ? 'catalog_category_entity' : 'catalog_product_entity'
        );

        $connection = $this->_getResourceConnection()->getConnection();
        $where = [
            'entity_type = ?' => $this->entityType,
            "entity_id NOT IN (SELECT entity_id FROM {$entityTable})",
        ];
        $this->_beginTransaction($connection);
        try {
            $oldRows = [];
            if ($this->changeListener !== null) {
                $select = $connection->select()->from($this->_getMainTableName());
                foreach ($where as $condition => $value) {
                    is_int($condition) ? $select->where($value) : $select->where($condition, $value);
                }
                $oldRows = $connection->fetchAll($select);
            }
            $connection->delete($this->_getMainTableName(), $where);
            $this->_commitTransaction($connection);

            $this->_queueRewriteChanges($oldRows, []);
        } catch (\Exception $e) {
            $this->_rollBackTransaction($connection);
            $this->_addFailure($this->entityType, null, null, 'deleting orphaned rewrites failed: ' . $e->getMessage());
        }
        $this->_flushChanges();

        return $this;
    }

    /**
     * Update "catalog_url_rewrite_product_category" table
     *
     * @return $this
     */
    protected function _updateSecondaryTable(): static
    {
        $this->_beginTransaction($this->_getResourceConnection()->getConnection());
        try {
            $this->_getResourceConnection()->getConnection()->delete(
                $this->_getSecondaryTableName(),
                "url_rewrite_id NOT IN (SELECT url_rewrite_id FROM {$this->_getMainTableName()})"
            );
            $this->_commitTransaction($this->_getResourceConnection()->getConnection());

        } catch (\Exception $e) {
            $this->_rollBackTransaction($this->_getResourceConnection()->getConnection());
            $this->_addFailure(
                $this->entityType,
                null,
                null,
                'cleaning the product/category rewrite table failed: ' . $e->getMessage()
            );
        }

        $select = $this->_getResourceConnection()->getConnection()->select()
            ->from(
                $this->_getMainTableName(),
                [
                    'url_rewrite_id',
                    'category_id' => new \Zend_Db_Expr(
                        'SUBSTRING_INDEX(SUBSTRING_INDEX(' . $this->_getMainTableName() . '.metadata, \'"\', -2), \'"\', 1)'
                    ),
                    'product_id' => 'entity_id'
                ]
            )
            ->where('metadata LIKE \'{"category_id":"%"}\'')
            ->where("url_rewrite_id NOT IN (SELECT url_rewrite_id FROM {$this->_getSecondaryTableName()})");
        try {
            $data = $this->_getResourceConnection()->getConnection()->fetchAll($select);
        } catch (\Exception $e) {
            $this->_addFailure(
                $this->entityType,
                null,
                null,
                'reading rewrites for the product/category rewrite table failed: ' . $e->getMessage()
            );

            return $this;
        }

        if (!empty($data)) {
            // I'm using row-by-row inserts because some products/categories not exists in entity tables but Url Rewrites
            // for this entity still exists in url_rewrite DB table.
            // This is the issue of Magento EE (Data integrity/assurance of the accuracy and consistency of data),
            // and this extension was made to not fix this; I just avoid this issue
            foreach ($data as $row) {
                $this->_beginTransaction($this->_getResourceConnection()->getConnection());
                try {
                    $this->_getResourceConnection()->getConnection()->insertOnDuplicate(
                        $this->_getSecondaryTableName(),
                        $row,
                        ['product_id']
                    );
                    $this->_commitTransaction($this->_getResourceConnection()->getConnection());

                } catch (\Exception $e) {
                    $this->_rollBackTransaction($this->_getResourceConnection()->getConnection());
                }
            }
        }

        return $this;
    }

    /**
     * Inside a caller's transaction (e.g. a dry run) use a savepoint: a nested adapter rollBack() would mark the
     * caller's transaction as failed and make every later beginTransaction() of the process throw
     *
     * @param AdapterInterface $connection
     * @return void
     */
    protected function _beginTransaction(AdapterInterface $connection): void
    {
        if ($connection->getTransactionLevel() > 0) {
            if ($this->transactionLost) {
                // as Magento's adapter refuses new transactions after a nested rollback
                throw new \RuntimeException(self::ERROR_TRANSACTION_LOST);
            }
            $savepoint = 'okrur_' . count($this->transactionStack);
            $connection->query('SAVEPOINT ' . $savepoint);
            $this->transactionStack[] = $savepoint;

            return;
        }

        $this->transactionLost = false;
        $connection->beginTransaction();
        $this->transactionStack[] = null;
    }

    /**
     * @param AdapterInterface $connection
     * @return void
     */
    protected function _commitTransaction(AdapterInterface $connection): void
    {
        $savepoint = array_pop($this->transactionStack);
        if ($savepoint === null) {
            $connection->commit();
        } else {
            $connection->query('RELEASE SAVEPOINT ' . $savepoint);
        }
    }

    /**
     * @param AdapterInterface $connection
     * @return void
     */
    protected function _rollBackTransaction(AdapterInterface $connection): void
    {
        $savepoint = array_pop($this->transactionStack);
        if ($savepoint === null) {
            $connection->rollBack();

            return;
        }

        try {
            $connection->query('ROLLBACK TO SAVEPOINT ' . $savepoint);
        } catch (\Exception $e) {
            // the server already ended the transaction (e.g. a deadlock rolled it back): nothing left to undo here,
            // and no further write may run until the caller ends its transaction
            $this->transactionLost = true;
        }
    }

    /**
     * @param array $urlRewrites
     * @return array
     */
    protected function _prepareUrlRewrites(array $urlRewrites): array
    {
        $result = [];
        $preserved = [];
        // "store|path" of preserved rows: a generated path must not take one of them over
        $reservedPaths = [];
        // "store|path Magento generated" => path it was actually saved under (clean-up, dedup index)
        $finalPaths = [];

        // non-autogenerated rows are admin-created custom rewrites or old-URL redirects kept by
        // --save-old-urls, re-emitted by Magento's generator: their request path must stay exactly
        // as it is (no sanitizing, no dedup index), or the URL they exist for is lost
        foreach ($urlRewrites as $urlRewrite) {
            if (!$urlRewrite->getIsAutogenerated()) {
                $rewrite = $urlRewrite->toArray();
                $preserved[] = $rewrite;
                $reservedPaths[$rewrite['store_id'] . '|' . $rewrite['request_path']] = true;
            }
        }

        foreach ($urlRewrites as $urlRewrite) {
            if (!$urlRewrite->getIsAutogenerated()) {
                continue;
            }
            $rewrite = $urlRewrite->toArray();

            // check if the same Url Rewrite already exists
            $originalRequestPath = trim($rewrite['request_path']);

            // skip empty Url Rewrites - I don't know how this possible, but it happens in Magento:
            // maybe someone did import product programmatically and product(s) name(s) are empty
            if (empty($originalRequestPath)) continue;

            // split generated Url Rewrite into parts
            $pathParts = pathinfo($originalRequestPath);

            // remove leading/trailing slashes and dots from parts
            $pathParts['dirname'] = trim($pathParts['dirname'], './');
            $pathParts['filename'] = trim($pathParts['filename'], './');

            // If the last symbol was slash - let's use it as url suffix
            $urlSuffix = substr($originalRequestPath, -1) === '/' ? '/' : '';

            // re-set Url Rewrite with sanitized parts
            $rewrite['request_path'] = $this->_mergePartsIntoRewriteRequest($pathParts, '', $urlSuffix);

            // check if we have a duplicate (maybe exists product with the same name => same Url Rewrite)
            // if exists then add additional index to avoid a duplicates
            $index = 0;
            while (
                isset($reservedPaths[$rewrite['store_id'] . '|' . $rewrite['request_path']])
                || $this->_urlRewriteExists($rewrite)
            ) {
                $index++;
                $rewrite['request_path'] = $this->_mergePartsIntoRewriteRequest($pathParts, (string)$index, $urlSuffix);
            }

            $finalPaths[$rewrite['store_id'] . '|' . $originalRequestPath] = $rewrite['request_path'];
            $result[] = $rewrite;
        }

        // Magento points a preserved redirect at the path it generated; follow it to where that path was
        // actually saved, or the redirect lands on a URL that no longer exists (e.g. after a dedup index)
        foreach ($preserved as $rewrite) {
            $generatedTarget = $rewrite['store_id'] . '|' . $rewrite['target_path'];
            if ($rewrite['redirect_type'] && isset($finalPaths[$generatedTarget])) {
                $rewrite['target_path'] = $finalPaths[$generatedTarget];
            }
            $result[] = $rewrite;
        }

        return $result;
    }

    /**
     * Check if Url Rewrite with the same request path exists
     *
     * @param array $rewrite
     * @return string
     */
    protected function _urlRewriteExists(array $rewrite): string|false
    {
        $select = $this->_getResourceConnection()->getConnection()->select()
            ->from($this->_getMainTableName(), ['url_rewrite_id'])
            ->where('entity_type = ?', $rewrite['entity_type'])
            ->where('request_path = ?', $rewrite['request_path'])
            ->where('store_id = ?', $rewrite['store_id'])
            ->where('entity_id != ?', $rewrite['entity_id']);
        return $this->_getResourceConnection()->getConnection()->fetchOne($select);
    }

    /**
     * Check if any Url Rewrite already exists for this entity/store, regardless of request_path
     * (used by --skip-existing, see #50)
     *
     * In the default-scope-only pass (store 0 of an all-stores run) "existing" means in any store: that
     * pass changes the shared default url_key/url_path, so an entity the store views will skip must not
     * be touched there either, or its attributes and rewrites drift apart.
     *
     * @param int $entityId
     * @param int $storeId
     * @return bool
     */
    protected function _urlRewriteExistsForEntity(int $entityId, int $storeId): bool
    {
        $select = $this->_getResourceConnection()->getConnection()->select()
            ->from($this->_getMainTableName(), ['url_rewrite_id'])
            ->where('entity_type = ?', $this->entityType)
            ->where('entity_id = ?', $entityId);
        if (!$this->regenerateOptions['defaultScopeOnly']) {
            $select->where('store_id = ?', $storeId);
        }
        return (bool)$this->_getResourceConnection()->getConnection()->fetchOne($select);
    }

    /**
     * Remove a store-level url_key so the store inherits the default-scope one — for a regenerated key equal to the
     * default: not writing it avoids a redundant override (see #92), but a stale override left in place would
     * disagree with the URL just generated from the regenerated key
     *
     * @param AbstractModel $entity product/category as loaded by its collection (incl. its link field)
     * @param int $storeId a store view, not 0
     * @return void
     */
    protected function _deleteStoreUrlKey(AbstractModel $entity, int $storeId): void
    {
        $resource = $entity->getResource();
        $attribute = $resource->getAttribute('url_key');
        // the link field (row_id on Adobe Commerce, entity_id otherwise), as Magento's own EAV writes use
        $linkField = $resource->getLinkField();

        $resource->getConnection()->delete($attribute->getBackend()->getTable(), [
            'attribute_id = ?' => (int)$attribute->getId(),
            $linkField . ' = ?' => (int)$entity->getData($linkField),
            'store_id = ?' => $storeId,
        ]);
    }

    /**
     * Merge Url Rewrite parts into one string
     *
     * @param array $pathParts
     * @param string $index
     * @param string $urlSuffix
     * @return string
     */
    protected function _mergePartsIntoRewriteRequest(array $pathParts, string $index = '', string $urlSuffix = ''): string
    {
        return (!empty($pathParts['dirname']) ? $pathParts['dirname'] . '/' : '') . $pathParts['filename']
            . (!empty($index) ? '-' . $index : '')
            . (!empty($pathParts['extension']) ? '.' . $pathParts['extension'] : '')
            . ($urlSuffix ?: '');
    }

    /**
     * Get root category I'd of specific store
     *
     * @param int $storeId
     * @return int|null
     */
    protected function _getStoreRootCategoryId(int $storeId): ?int
    {
        if (empty($this->storeRootCategoryId[$storeId])) {
            $value = null;
            try {
                $store = $this->helper->getStoreManager()->getStore($storeId);
                if ($store) {
                    $value = $store->getRootCategoryId();
                }
            } catch (\Exception $e) {
            }

            $this->storeRootCategoryId[$storeId] = $value;
        }

        return $this->storeRootCategoryId[$storeId];
    }
}
