<?php
/**
 * RegenerateTest.php
 *
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2026
 */

namespace OlegKoval\RegenerateUrlRewrites\Test\Unit\Helper;

use Magento\Framework\Serialize\Serializer\Json;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use OlegKoval\RegenerateUrlRewrites\Helper\Regenerate;
use PHPUnit\Framework\TestCase;

class RegenerateTest extends TestCase
{
    /**
     * @var Regenerate
     */
    private $helper;

    /**
     * @return void
     */
    protected function setUp(): void
    {
        $this->helper = (new \ReflectionClass(Regenerate::class))->newInstanceWithoutConstructor();
    }

    /**
     * @return void
     */
    public function testSamePathInDifferentStoresIsNotADuplicate(): void
    {
        $result = $this->helper->sanitizeProductUrlRewrites(
            [$this->rewrite(1, 'item.html'), $this->rewrite(2, 'item.html')]
        );

        self::assertSame([1, 2], array_map(fn (UrlRewrite $r): int => (int)$r->getStoreId(), array_values($result)));
    }

    /**
     * @return void
     */
    public function testSamePathInTheSameStoreIsDroppedAsDuplicate(): void
    {
        $result = $this->helper->sanitizeProductUrlRewrites(
            [$this->rewrite(1, 'item.html'), $this->rewrite(1, '/item.html')]
        );

        self::assertCount(1, $result);
    }

    /**
     * @return void
     */
    public function testGeneratedPathsAreCleanedUp(): void
    {
        $result = $this->helper->sanitizeProductUrlRewrites([$this->rewrite(1, '/./gear//bags.html')]);

        self::assertSame('gear/bags.html', array_values($result)[0]->getRequestPath());
    }

    /**
     * @return void
     */
    public function testCustomRowsAreLeftExactlyAsTheyAre(): void
    {
        $custom = $this->rewrite(1, '.well-known//x', false);
        $result = $this->helper->sanitizeProductUrlRewrites([$this->rewrite(1, '.well-known//x'), $custom]);

        self::assertContains($custom, $result);
        self::assertSame('.well-known//x', $custom->getRequestPath());
    }

    /**
     * @param int $storeId
     * @param string $requestPath
     * @param bool $autogenerated
     * @return UrlRewrite
     */
    private function rewrite(int $storeId, string $requestPath, bool $autogenerated = true): UrlRewrite
    {
        return (new UrlRewrite([], new Json()))
            ->setEntityType('product')
            ->setEntityId(1)
            ->setStoreId($storeId)
            ->setRequestPath($requestPath)
            ->setTargetPath('catalog/product/view/id/1')
            ->setIsAutogenerated((int)$autogenerated);
    }
}
