<?php
/**
 * ConsoleChangeReporter.php
 *
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2026
 */

namespace OlegKoval\RegenerateUrlRewrites\Console;

use OlegKoval\RegenerateUrlRewrites\Api\ChangeListenerInterface;
use OlegKoval\RegenerateUrlRewrites\Api\Data\ChangeInterface;
use Symfony\Component\Console\Formatter\OutputFormatter;

/**
 * Counts a run's changes and, if asked, prints one line per change (the command's -v output, see #91)
 */
class ConsoleChangeReporter implements ChangeListenerInterface
{
    /**
     * Columns compared for a rewrite_updated line (request path and store are the same by definition)
     */
    private const UPDATED_COLUMNS = ['target_path', 'redirect_type', 'entity_type', 'entity_id', 'is_autogenerated',
        'description', 'metadata'];

    /**
     * Summary label per type, in summary order
     */
    private const SUMMARY_LABELS = [
        ChangeInterface::TYPE_REWRITE_ADDED => 'rewrite(s) added',
        ChangeInterface::TYPE_REWRITE_REMOVED => 'removed',
        ChangeInterface::TYPE_REWRITE_UPDATED => 'updated',
        ChangeInterface::TYPE_URL_KEY_CHANGED => 'url_key',
        ChangeInterface::TYPE_URL_PATH_CHANGED => 'url_path',
    ];

    /**
     * @var ConsoleProgressReporter
     */
    private ConsoleProgressReporter $progressReporter;

    /**
     * @var bool
     */
    private bool $printChanges;

    /**
     * @var array<string, int> type => count
     */
    private array $counts = [];

    /**
     * @param ConsoleProgressReporter $progressReporter writes the lines without breaking the progress bar
     * @param bool $printChanges false: only count, for the summary
     */
    public function __construct(ConsoleProgressReporter $progressReporter, bool $printChanges)
    {
        $this->progressReporter = $progressReporter;
        $this->printChanges = $printChanges;
    }

    /**
     * @param ChangeInterface $change
     * @return void
     */
    public function onChange(ChangeInterface $change): void
    {
        $this->counts[$change->getType()] = ($this->counts[$change->getType()] ?? 0) + 1;
        if ($this->printChanges) {
            $this->progressReporter->line('  ' . OutputFormatter::escape($this->format($change)));
        }
    }

    /**
     * E.g. "Changes: 12 rewrite(s) added, 3 removed, 5 url_key" (types without changes left out)
     *
     * @return string
     */
    public function getSummary(): string
    {
        $parts = [];
        foreach (self::SUMMARY_LABELS as $type => $label) {
            if (isset($this->counts[$type])) {
                $parts[] = $this->counts[$type] . ' ' . $label;
            }
        }

        return 'Changes: ' . ($parts ? implode(', ', $parts) : 'none');
    }

    /**
     * @param ChangeInterface $change
     * @return string
     */
    public function format(ChangeInterface $change): string
    {
        $subject = $change->getEntityType() . ' ' . $change->getEntityId() . ' (store ' . $change->getStoreId() . ')';

        switch ($change->getType()) {
            case ChangeInterface::TYPE_REWRITE_ADDED:
                return '+ ' . $subject . ': ' . $this->formatRewrite($change->getNewRewrite());
            case ChangeInterface::TYPE_REWRITE_REMOVED:
                return '- ' . $subject . ': ' . $this->formatRewrite($change->getOldRewrite());
            case ChangeInterface::TYPE_REWRITE_UPDATED:
                return '~ ' . $subject . ': ' . $change->getNewValue() . ': '
                    . $this->formatUpdate($change->getOldRewrite(), $change->getNewRewrite());
            default:
                $attribute = $change->getType() === ChangeInterface::TYPE_URL_KEY_CHANGED ? 'url_key' : 'url_path';

                return $attribute . ' ' . $subject . ': '
                    . $this->formatValue($change->hasOldRow(), $change->getOldValue()) . ' -> '
                    . $this->formatValue($change->hasNewRow(), $change->getNewValue());
        }
    }

    /**
     * @param array<string, mixed>|null $rewrite
     * @return string request path, plus its target for a redirect
     */
    private function formatRewrite(?array $rewrite): string
    {
        $text = (string)($rewrite['request_path'] ?? '');
        if ((int)($rewrite['redirect_type'] ?? 0) > 0) {
            $text .= ' -> ' . $rewrite['redirect_type'] . ' ' . $rewrite['target_path'];
        }

        return $text;
    }

    /**
     * @param array<string, mixed>|null $old
     * @param array<string, mixed>|null $new
     * @return string the differing columns, e.g. "target_path a -> b, redirect_type 0 -> 301"
     */
    private function formatUpdate(?array $old, ?array $new): string
    {
        $parts = [];
        foreach (self::UPDATED_COLUMNS as $column) {
            $oldValue = $this->formatColumn($old[$column] ?? null);
            $newValue = $this->formatColumn($new[$column] ?? null);
            if ($oldValue !== $newValue) {
                $parts[] = $column . ' ' . $oldValue . ' -> ' . $newValue;
            }
        }

        return implode(', ', $parts);
    }

    /**
     * @param mixed $value
     * @return string
     */
    private function formatColumn(mixed $value): string
    {
        if ($value === null) {
            return 'null';
        }

        return is_array($value) ? (string)json_encode($value) : (string)$value;
    }

    /**
     * @param bool $rowExists
     * @param string|null $value
     * @return string "(none)" for no row, so a stored NULL (a store-level reset) stays distinguishable
     */
    private function formatValue(bool $rowExists, ?string $value): string
    {
        if (!$rowExists) {
            return '(none)';
        }

        return $value === null ? 'null' : '"' . $value . '"';
    }
}
