<?php
/**
 * ChangeInterface.php
 *
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2026
 */

namespace OlegKoval\RegenerateUrlRewrites\Api\Data;

/**
 * One DB change of a regeneration run, as passed to \OlegKoval\RegenerateUrlRewrites\Api\ChangeListenerInterface
 *
 * Implemented only by this module, so it may gain methods in minor releases; don't implement it yourself.
 *
 * @api
 */
interface ChangeInterface
{
    public const TYPE_REWRITE_ADDED = 'rewrite_added';
    public const TYPE_REWRITE_REMOVED = 'rewrite_removed';
    /** Same store and request path, other columns changed (e.g. target path, redirect type) */
    public const TYPE_REWRITE_UPDATED = 'rewrite_updated';
    public const TYPE_URL_KEY_CHANGED = 'url_key_changed';
    public const TYPE_URL_PATH_CHANGED = 'url_path_changed';

    /**
     * @return string one of the TYPE_* constants
     */
    public function getType(): string;

    /**
     * @return string "product" or "category" (for a rewrite: its entity_type column)
     */
    public function getEntityType(): string;

    /**
     * @return int|null
     */
    public function getEntityId(): ?int;

    /**
     * For rewrite types the rewrite's store; for url_key/url_path types the store of the attribute row written —
     * 0 = default scope, which may differ from the store the run was processing
     *
     * @return int
     */
    public function getStoreId(): int;

    /**
     * @return string|null the request path (rewrite types) or attribute value before the change; null = none/inherited
     */
    public function getOldValue(): ?string;

    /**
     * @return string|null the request path (rewrite types) or attribute value after the change; null = none/inherited
     */
    public function getNewValue(): ?string;

    /**
     * Whether the row existed before the change: for attribute types a row may exist and hold NULL (a store-level
     * reset), which getOldValue() alone can't tell from no row; for rewrite types the same as getOldRewrite() !== null
     *
     * @return bool
     */
    public function hasOldRow(): bool;

    /**
     * Whether the row exists after the change (see hasOldRow())
     *
     * @return bool
     */
    public function hasNewRow(): bool;

    /**
     * The url_rewrite row before the change (rewrite types; null for rewrite_added and attribute types), keyed
     * request_path, target_path, redirect_type, store_id, entity_type, entity_id, is_autogenerated, description,
     * metadata (decoded array or null) — no url_rewrite_id
     *
     * @return array<string, mixed>|null
     */
    public function getOldRewrite(): ?array;

    /**
     * The url_rewrite row after the change (as getOldRewrite(); null for rewrite_removed and attribute types)
     *
     * @return array<string, mixed>|null
     */
    public function getNewRewrite(): ?array;
}
