<?php
/**
 * ConsoleChangeReporterTest.php
 *
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2026
 */

namespace OlegKoval\RegenerateUrlRewrites\Test\Unit\Console;

use OlegKoval\RegenerateUrlRewrites\Api\Data\ChangeInterface;
use OlegKoval\RegenerateUrlRewrites\Console\ConsoleChangeReporter;
use OlegKoval\RegenerateUrlRewrites\Console\ConsoleProgressReporter;
use OlegKoval\RegenerateUrlRewrites\Model\Change;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Output\BufferedOutput;

class ConsoleChangeReporterTest extends TestCase
{
    /**
     * @return void
     */
    public function testEveryChangeTypeHasItsLine(): void
    {
        $output = new BufferedOutput();
        $reporter = new ConsoleChangeReporter(new ConsoleProgressReporter($output, false), true);

        $redirect = $this->rewrite('old.html', 'new.html', 301);
        foreach ([
            new Change(ChangeInterface::TYPE_REWRITE_ADDED, 'product', 12, 1, null, 'a.html', null,
                $this->rewrite('a.html', 'catalog/product/view/id/12', 0)),
            new Change(ChangeInterface::TYPE_REWRITE_ADDED, 'product', 12, 1, null, 'old.html', null, $redirect),
            new Change(ChangeInterface::TYPE_REWRITE_REMOVED, 'category', 3, 2, 'gone.html', null,
                $this->rewrite('gone.html', 'catalog/category/view/id/3', 0)),
            new Change(ChangeInterface::TYPE_REWRITE_UPDATED, 'product', 12, 1, 'old.html', 'old.html',
                $this->rewrite('old.html', 'x.html', 302), $redirect),
            new Change(ChangeInterface::TYPE_URL_KEY_CHANGED, 'product', 12, 0, 'old', 'new', null, null, true, true),
            new Change(ChangeInterface::TYPE_URL_KEY_CHANGED, 'product', 12, 1, 'old', null, null, null, true, false),
            new Change(ChangeInterface::TYPE_URL_PATH_CHANGED, 'category', 3, 1, null, 'a/<b>', null, null, true, true),
        ] as $change) {
            $reporter->onChange($change);
        }

        self::assertSame(
            "  + product 12 (store 1): a.html\n"
            . "  + product 12 (store 1): old.html -> 301 new.html\n"
            . "  - category 3 (store 2): gone.html\n"
            . "  ~ product 12 (store 1): old.html: target_path x.html -> new.html, redirect_type 302 -> 301\n"
            . "  url_key product 12 (store 0): \"old\" -> \"new\"\n"
            . "  url_key product 12 (store 1): \"old\" -> (none)\n"
            . "  url_path category 3 (store 1): null -> \"a/<b>\"\n",
            $output->fetch()
        );
        self::assertSame('Changes: 2 rewrite(s) added, 1 removed, 1 updated, 2 url_key, 1 url_path', $reporter->getSummary());
    }

    /**
     * @return void
     */
    public function testCountOnlyPrintsNothingAndAnEmptyRunHasNoChanges(): void
    {
        $output = new BufferedOutput();
        $reporter = new ConsoleChangeReporter(new ConsoleProgressReporter($output, false), false);

        self::assertSame('Changes: none', $reporter->getSummary());
        $reporter->onChange(new Change(ChangeInterface::TYPE_REWRITE_REMOVED, 'product', 1, 1, 'a.html', null,
            $this->rewrite('a.html', 't', 0)));

        self::assertSame('', $output->fetch());
        self::assertSame('Changes: 1 removed', $reporter->getSummary());
    }

    /**
     * @param string $requestPath
     * @param string $targetPath
     * @param int $redirectType
     * @return array<string, mixed>
     */
    private function rewrite(string $requestPath, string $targetPath, int $redirectType): array
    {
        return [
            'request_path' => $requestPath,
            'target_path' => $targetPath,
            'redirect_type' => $redirectType,
            'store_id' => 1,
            'entity_type' => 'product',
            'entity_id' => 12,
            'is_autogenerated' => 1,
            'description' => null,
            'metadata' => null,
        ];
    }
}
