<?php
/**
 * ChangeTrackingTest.php
 *
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2026
 */

namespace OlegKoval\RegenerateUrlRewrites\Test\Unit\Model;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\DB\Adapter\AdapterInterface;
use Magento\Framework\DB\Select;
use Magento\Framework\Serialize\Serializer\Json;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use OlegKoval\RegenerateUrlRewrites\Api\ChangeListenerInterface;
use OlegKoval\RegenerateUrlRewrites\Api\Data\ChangeInterface;
use OlegKoval\RegenerateUrlRewrites\Model\Change;
use OlegKoval\RegenerateUrlRewrites\Model\RegenerateProductRewrites;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class ChangeTrackingTest extends TestCase
{
    /**
     * @var AdapterInterface&MockObject
     */
    private $connection;

    /**
     * @var RegenerateProductRewrites
     */
    private $model;

    /**
     * @var ChangeInterface[]
     */
    private array $received = [];

    /**
     * @return void
     */
    protected function setUp(): void
    {
        $select = $this->createMock(Select::class);
        $select->method('from')->willReturnSelf();
        $select->method('where')->willReturnSelf();
        $this->connection = $this->createMock(AdapterInterface::class);
        $this->connection->method('select')->willReturn($select);
        $this->connection->method('quoteInto')->willReturnCallback(
            fn (string $text, $value): string => str_replace('?', "'" . $value . "'", $text)
        );
        $resource = $this->createMock(ResourceConnection::class);
        $resource->method('getConnection')->willReturn($this->connection);
        $resource->method('getTableName')->willReturnArgument(0);

        $this->model = new class ($resource) extends RegenerateProductRewrites {
            /**
             * @param ResourceConnection $resource
             */
            public function __construct(ResourceConnection $resource)
            {
                $this->resourceConnection = $resource;
                $this->regenerateOptions = $this->defaultRegenerateOptions;
            }

            /**
             * @param array $rewrite
             * @return string|false
             */
            protected function _urlRewriteExists(array $rewrite): string|false
            {
                return false;
            }
        };
        $this->model->setChangeListener($this->listener());
    }

    /**
     * @return void
     */
    public function testReplacingRowsReportsAddedRemovedAndUpdatedRewritesWithFullRows(): void
    {
        $this->invoke('_queueRewriteChanges', [
            $this->dbRow('kept.html', 'catalog/product/view/id/5'),
            $this->dbRow('old.html', 'catalog/product/view/id/5'),
            $this->dbRow('moved.html', 'catalog/product/view/id/5'),
            $this->dbRow('gear/moved.html', 'catalog/product/view/id/5/category/3', '{"category_id":"3"}'),
        ], [
            $this->dbRow('kept.html', 'catalog/product/view/id/5'),
            $this->dbRow('moved.html', 'new.html', null, 301, 0),
            $this->dbRow('gear/moved.html', 'catalog/product/view/id/5/category/3', '{"category_id":"3"}'),
            $this->dbRow('new.html', 'catalog/product/view/id/5'),
        ]);
        $this->invoke('_flushChanges');

        self::assertSame(
            [['rewrite_removed', 'old.html', null], ['rewrite_updated', 'moved.html', 'moved.html'],
                ['rewrite_added', null, 'new.html']],
            array_map(
                fn (ChangeInterface $c): array => [$c->getType(), $c->getOldValue(), $c->getNewValue()],
                $this->received
            )
        );
        $updated = $this->received[1];
        self::assertSame('catalog/product/view/id/5', $updated->getOldRewrite()['target_path']);
        self::assertSame(['new.html', 301, 0], [
            $updated->getNewRewrite()['target_path'],
            $updated->getNewRewrite()['redirect_type'],
            $updated->getNewRewrite()['is_autogenerated'],
        ]);
        self::assertSame(
            ['request_path', 'target_path', 'redirect_type', 'store_id', 'entity_type', 'entity_id', 'is_autogenerated',
                'description', 'metadata'],
            array_keys($this->received[0]->getOldRewrite())
        );
        self::assertSame(
            ['product', 5, 1],
            [$updated->getEntityType(), $updated->getEntityId(), $updated->getStoreId()]
        );
    }

    /**
     * @return void
     */
    public function testMetadataIsDecoded(): void
    {
        $this->invoke('_queueRewriteChanges', [], [$this->dbRow('gear/x.html', 't', '{"category_id":"3"}')]);
        $this->invoke('_flushChanges');

        self::assertSame(['category_id' => '3'], $this->received[0]->getNewRewrite()['metadata']);
    }

    /**
     * @return void
     */
    public function testASavedReplacementIsReportedAfterTheCommit(): void
    {
        $this->connection->method('fetchAll')->willReturnOnConsecutiveCalls(
            [$this->dbRow('old.html', 'catalog/product/view/id/5')],
            [$this->dbRow('new.html', 'catalog/product/view/id/5')]
        );
        $this->connection->expects(self::once())->method('commit');

        $this->model->saveUrlRewrites(
            [$this->rewrite('new.html')],
            [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]
        );
        self::assertSame([], $this->received, 'queued, not yet passed on');
        $this->invoke('_flushChanges');

        self::assertSame(
            ['rewrite_removed', 'rewrite_added'],
            array_map(fn (ChangeInterface $c): string => $c->getType(), $this->received)
        );
    }

    /**
     * @return void
     */
    public function testARowOfAnotherScopeUpdatedByTheSaveIsReportedAsItReallyIs(): void
    {
        // store 2 holds the path already (e.g. a sibling store view's row outside the replaced set);
        // insertOnDuplicate() updates only request_path/metadata there, so its target stays
        $sibling = $this->dbRow('item.html', 'catalog/product/view/id/5');
        $sibling['store_id'] = '2';
        $siblingAfter = $sibling;
        $siblingAfter['metadata'] = '{"category_id":"3"}';
        $this->connection->method('fetchAll')->willReturnOnConsecutiveCalls([$sibling], [$siblingAfter]);

        $row = $this->rewrite('item.html')->setStoreId(2);
        $this->model->saveUrlRewrites([$row], [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]);
        $this->invoke('_flushChanges');

        self::assertCount(1, $this->received);
        self::assertSame('rewrite_updated', $this->received[0]->getType());
        self::assertSame(['category_id' => '3'], $this->received[0]->getNewRewrite()['metadata']);
        self::assertSame('catalog/product/view/id/5', $this->received[0]->getNewRewrite()['target_path']);
    }

    /**
     * @return void
     */
    public function testARolledBackSaveReportsNothing(): void
    {
        $this->connection->method('fetchAll')->willReturn([$this->dbRow('old.html', 'catalog/product/view/id/5')]);
        $this->connection->method('insertOnDuplicate')->willThrowException(new \Exception('deadlock'));

        $this->model->saveUrlRewrites(
            [$this->rewrite('new.html')],
            [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]
        );
        $this->invoke('_flushChanges');

        self::assertSame([], $this->received);
        self::assertCount(1, $this->model->getFailures());
    }

    /**
     * @return void
     */
    public function testAFailedCommitReportsNothing(): void
    {
        $this->connection->method('fetchAll')->willReturnOnConsecutiveCalls(
            [$this->dbRow('old.html', 'catalog/product/view/id/5')],
            [$this->dbRow('new.html', 'catalog/product/view/id/5')]
        );
        $this->connection->method('commit')->willThrowException(new \Exception('lost connection'));

        $this->model->saveUrlRewrites(
            [$this->rewrite('new.html')],
            [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]
        );
        $this->invoke('_flushChanges');

        self::assertSame([], $this->received);
    }

    /**
     * @return void
     */
    public function testAFailingReadAfterTheCommitKeepsTheSaveAndReportsATrackingFailure(): void
    {
        $this->connection->method('fetchAll')->willReturnCallback(function (): array {
            static $calls = 0;
            if (++$calls === 2) {
                throw new \Exception('read timeout');
            }
            return [];
        });
        $this->connection->expects(self::once())->method('commit');
        $this->connection->expects(self::never())->method('rollBack');

        $this->model->saveUrlRewrites(
            [$this->rewrite('new.html')],
            [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]
        );

        $failures = $this->model->getFailures();
        self::assertCount(1, $failures);
        self::assertStringContainsString('URL rewrites saved, but reading them', $failures[0]['message']);
    }

    /**
     * @return void
     */
    public function testWithoutAListenerNothingIsReadOrQueued(): void
    {
        $this->model->setChangeListener(null);
        $this->connection->expects(self::never())->method('fetchAll');

        $this->model->saveUrlRewrites(
            [$this->rewrite('new.html')],
            [['entity_type' => 'product', 'entity_id' => 5, 'store_id' => 1]]
        );

        self::assertSame([], (fn (): array => $this->pendingChanges)->call($this->model));
    }

    /**
     * @return void
     */
    public function testAttributeChangesCarryTheScopeOfTheRowWritten(): void
    {
        $entity = $this->createConfiguredMock(\Magento\Catalog\Model\Product::class, ['getId' => 5]);

        $this->invoke(
            '_queueAttributeChanges',
            $entity,
            [
                'url_key' => [0 => [true, 'bag'], 2 => [true, 'stale']],
                'url_path' => [0 => [false, null], 2 => [false, null]],
            ],
            [
                'url_key' => [0 => [true, 'bag'], 2 => [false, null]],
                'url_path' => [0 => [true, 'gear/bag'], 2 => [true, null]],
            ]
        );
        $this->invoke('_flushChanges');

        self::assertSame(
            [['url_key_changed', 2, 'stale', null], ['url_path_changed', 0, null, 'gear/bag'],
                ['url_path_changed', 2, null, null]],
            array_map(
                fn (ChangeInterface $c): array => [
                    $c->getType(),
                    $c->getStoreId(),
                    $c->getOldValue(),
                    $c->getNewValue(),
                ],
                $this->received
            )
        );
        self::assertNull($this->received[0]->getOldRewrite());
        self::assertSame([true, false], [$this->received[0]->hasOldRow(), $this->received[0]->hasNewRow()]);
        self::assertSame(
            [false, true],
            [$this->received[2]->hasOldRow(), $this->received[2]->hasNewRow()],
            'a NULL-valued row created where none was'
        );
    }

    /**
     * @return void
     */
    public function testAnExceptionFromTheListenerLeavesTheQueueEmpty(): void
    {
        $this->model->setChangeListener(new class () implements ChangeListenerInterface {
            /**
             * @param ChangeInterface $change
             * @return void
             */
            public function onChange(ChangeInterface $change): void
            {
                throw new \RuntimeException('stop');
            }
        });
        (fn () => $this->pendingChanges = [new Change('rewrite_added', 'product', 1, 1, null, 'a.html')])
            ->call($this->model);

        try {
            $this->invoke('_flushChanges');
            self::fail('the listener exception is expected to propagate');
        } catch (\RuntimeException $e) {
            self::assertSame('stop', $e->getMessage());
        }
        self::assertSame([], (fn (): array => $this->pendingChanges)->call($this->model));
    }

    /**
     * @param string $requestPath
     * @param string $targetPath
     * @param string|null $metadata
     * @param int $redirectType
     * @param int $autogenerated
     * @return array
     */
    private function dbRow(
        string $requestPath,
        string $targetPath,
        ?string $metadata = null,
        int $redirectType = 0,
        int $autogenerated = 1
    ): array {
        return [
            'url_rewrite_id' => '77',
            'entity_type' => 'product',
            'entity_id' => '5',
            'request_path' => $requestPath,
            'target_path' => $targetPath,
            'redirect_type' => (string)$redirectType,
            'store_id' => '1',
            'description' => null,
            'is_autogenerated' => (string)$autogenerated,
            'metadata' => $metadata,
        ];
    }

    /**
     * @param string $requestPath
     * @return UrlRewrite
     */
    private function rewrite(string $requestPath): UrlRewrite
    {
        return (new UrlRewrite([], new Json()))
            ->setEntityType('product')
            ->setEntityId(5)
            ->setStoreId(1)
            ->setRequestPath($requestPath)
            ->setTargetPath('catalog/product/view/id/5')
            ->setRedirectType(0)
            ->setIsAutogenerated(1);
    }

    /**
     * @return ChangeListenerInterface
     */
    private function listener(): ChangeListenerInterface
    {
        $received = &$this->received;

        return new class ($received) implements ChangeListenerInterface {
            /**
             * @param array $received
             */
            public function __construct(private array &$received)
            {
            }

            /**
             * @param ChangeInterface $change
             * @return void
             */
            public function onChange(ChangeInterface $change): void
            {
                $this->received[] = $change;
            }
        };
    }

    /**
     * @param string $method
     * @param mixed ...$args
     * @return mixed
     */
    private function invoke(string $method, mixed ...$args): mixed
    {
        return (new \ReflectionMethod($this->model, $method))->invoke($this->model, ...$args);
    }
}
